version: "3.9"
services:
    bg:
        image: asiusj/clnme-test:bg
        container_name: bg
        restart: unless-stopped
        env_file: .env
        ports:
            - "8000:1337"
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        depends_on:
            - mongo
    mongo:
        image: asiusj/clnme-test:mongo
        container_name: data-base
        restart: unless-stopped
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"

    frontend:
        image: asiusj/clnme-test:front
        container_name: frontend
        restart: unless-stopped
        env_file: .prod.env
        network_mode: host

